In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=64, activation='relu', input_shape=(100,)))


for i in range(10):
    model.add(Dense(units=64, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = W * 0.1          # W = W * 0.1
        layer.set_weights([W, b])



In [ ]:
W, b = model.layers[0].get_weights()
print(W.mean(), W.std())


0.00027711192 0.011081619


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = W * 5          # W = W * 0.5
        layer.set_weights([W, b])


W, b = model.layers[0].get_weights()
print(W.mean(), W.std())

0.006927799 0.27704048


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = W * 0          # W = W * 0
        layer.set_weights([W, b])


W, b = model.layers[0].get_weights()
print(W.mean(), W.std())

0.0 0.0


In [ ]:
import numpy as np

for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = np.full_like(W, 0.1)   # same shape as W
        b = np.zeros_like(b)       # optional: reset biases
        layer.set_weights([W, b])



W, b = model.layers[0].get_weights()
print(W.mean(), W.std())

0.10000002 1.4901161e-08


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(
    64,
    activation='relu',
    input_shape=(100,),
    kernel_initializer='he_normal'
))

for _ in range(10):
    model.add(Dense(
        64,
        activation='relu',
        kernel_initializer='he_normal'
    ))

model.add(Dense(
    1,
    activation='sigmoid',
    kernel_initializer='glorot_uniform'  # standard for sigmoid
))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def create_dnn():
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(100,)))

    for _ in range(9):   # total hidden layers = 10
        model.add(Dense(64, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))
    return model

model = create_dnn()


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = W * 0.1
        layer.set_weights([W, b])


In [ ]:
print(W,b)

[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]] [0.]


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = W * 5
        layer.set_weights([W, b])
print(W,b)

[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]] [0.]


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = np.zeros_like(W)
        layer.set_weights([W, b])
print(W,b)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] [0.]


In [ ]:
for layer in model.layers:
    if isinstance(layer, Dense):
        W, b = layer.get_weights()
        W = np.full_like(W, 0.1)
        layer.set_weights([W, b])
print(W,b)

[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]] [0.]


In [ ]:
model_xavier = Sequential()
model_xavier.add(Dense(
    64, activation='tanh',
    input_shape=(100,),
    kernel_initializer='glorot_uniform'
))

for _ in range(9):
    model_xavier.add(Dense(
        64, activation='tanh',
        kernel_initializer='glorot_uniform'
    ))

model_xavier.add(Dense(1, activation='sigmoid'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model_he = Sequential()
model_he.add(Dense(
    64, activation='relu',
    input_shape=(100,),
    kernel_initializer='he_normal'
))

for _ in range(9):
    model_he.add(Dense(
        64, activation='relu',
        kernel_initializer='he_normal'
    ))

model_he.add(Dense(1, activation='sigmoid'))
